apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "leaveat.fullname" . }}-frontend
  labels:
    app: {{ include "leaveat.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "leaveat.name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "leaveat.name" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.frontend.port }}
          {{- with .Values.frontend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
