apiVersion: v1
kind: Service
metadata:
  name: {{ include "leaveat.licenseName" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "leaveat.licenseName" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.license.port }}
      targetPort: {{ .Values.license.port }}