{{- if .Values.redis.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "leaveat.fullname" . }}-redis-secret
  labels:
    app: {{ include "leaveat.name" . }}-redis
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  REDIS_URL: {{ printf "redis://:%s@%s-redis:6379" .Values.redis.password (include "leaveat.fullname" .) | quote }}
{{- end }}