FROM node:20-alpine

ARG NPM_TOKEN

WORKDIR /usr/src/app

COPY package*.json ./
RUN echo "@epheme:registry=https://npm.sillygooseia.com" >> .npmrc && \
    echo "//npm.sillygooseia.com/:_authToken=${NPM_TOKEN}" >> .npmrc && \
    npm install && \
    rm -f .npmrc

COPY . ./

EXPOSE 3001

CMD ["npm", "run", "dev"]
